### PR TITLE
make the looker sdk great again

### PR DESCRIPTION
**Pull request by ryantuck**
fix issues with import the `re` module and bad referencing of the `self.sorts` member variable

### CODE REVIEW

**Comment by vivitsu** [comment]
:+1: Ok to merge.

**Comment by schwallie2** [comment]
@ryantuck care to merge this?

**Comment by kahnjw** [comment]
Can this be merged. I am running into the bad `sorts` reference.

**Comment by mattgmarcus** [comment]
@ryantuck @schwallie2 @kahnjw - sorry for the delay on this. just merged it into master for you all

**Pull request merged**
